### ISSUE TITLE
Does not work for inputs where the value is binded to a variable.

### ISSUE THREAD

**Issue by Blankeos** [noahsalvi/svelte-use-form#65] opened 2023-09-17 11:43 UTC
```svelte
<script>
let name = "Carl";
</script>

<input name="name" bind:value={name} />
```

Changing the value of name via javascript instead of typing does not update the store correctly.

**Comment by noahsalvi** [comment] 2023-09-17 13:32
I believe that this is a duplicate of #60.

However, I'm open to suggestions if you see a possible solution to it.

**Closed by noahsalvi** 2023-09-17 13:32 UTC
